version: "3"
services:
  my_game_api:
    image: isabellaf16/hgop-api:${GIT_COMMIT}
    ports:
      - "3000:3000"
    depends_on:
      - my_database_container
    environment:
      PORT: 3000
      POSTGRES_HOST: "my_database_container"
      POSTGRES_DB: "game_database"
      POSTGRES_USER: "my_user"
      POSTGRES_PASSWORD: "my_password"
      ENVIRONMENT: ${ENVIRONMENT}
  my_database_container:
    image: postgres
    environment:
      POSTGRES_DB: "game_database"
      POSTGRES_USER: "my_user"
      POSTGRES_PASSWORD: "my_password"
  my_client_container:
    image: isabellaf16/hgop-client:${GIT_COMMIT}
    ports:
      - "4000:4000"
    depends_on:
      - my_game_api
    environment:
      PORT: 4000
      API_URL: ${API_URL}
  # Based on https://github.com/DataDog/docker-compose-example
  my_datadog_container:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=a724b389c9c4f658bdf284272d2e306d
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_TAGS=${ENVIRONMENT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
